### ISSUE TITLE
【意见建议】针对文档开发指南模块

### ISSUE THREAD

**Issue by humorwang** [XTLS/Xray-docs-next#19]
能否在文档 开发指南模块更加详细写一下项目的组织结构以及各个模块之间的关联关系，以及如何构建二次开发？尽管有一定的开发经验，也能写一些crud的golang代码，但想在项目核心功能不变的基础上在应用层进行一些二次开发依然觉得无从下手。也不知道是我太笨还是很多人也有同样的感受。我看代码维护多是几位核心大佬再搞，外围开发者感觉比较难于融入进来。

**Comment by rurirei** [comment]
> 我看代码维护多是几位核心大佬再搞，外围开发者感觉比较难于融入进来。

agreed.

**Comment by rprx** [comment]
相信我，不是你的问题，那些代码就是写得很难接手，所以我准备大规模重构它们

在文档相关仓库的第一个操作达成 √

从现在开始我要接手、整合文档的建设了，因为之前两位分别弄新旧文档的均已...

**Comment by humorwang** [comment]
> 相信我，不是你的问题，那些代码就是写得很难接手，所以我准备大规模重构它们
> 
> 在文档相关仓库的第一个操作达成 √
> 
> 从现在开始我要接手、整合文档的建设了，因为之前两位分别弄新旧文档的均已...

大佬您真的辛苦了，每天不停输出，还能持续保持高质量输出，真的是我们学习的榜样。

**Comment by JimhHan** [comment]
> 因为之前两位分别弄新旧文档的均已...

如果 vuepress-next 有 breaking change 我会 pr。

**Comment by Fangliding** [comment]
v2ray-core
├── app        // 应用模块
│   ├── router // 路由
├── common     // 公用代码
├── proxy      // 通讯协议
│   ├── blackhole
│   ├── dokodemo-door
│   ├── freedom
│   ├── socks
│   ├── vmess
│   ├── ...........
├── transport  // 传输模块
