### ISSUE TITLE
关于透明代理中的ipv6 Netfilter设置

### ISSUE THREAD

**Issue by 763ce67512c8** [XTLS/Xray-docs-next#204]
在透明代理的ipv6 Netfilter 设置部分需要输入`网关IPv6地址段`参数，但由于目前ipv6的地址段都是动态分配，写入的规则在变更后会失效，是否有无需填写地址段的设置方法？

**Comment by Fangliding** [comment]
那是个ULA地址吧 应该不会变 如果自己搓的方案麻烦自己想办法(
