### ISSUE TITLE
小小白白话文第7章 配置证书可能出现出现失败的情况

### ISSUE THREAD

**Issue by IceInfinite** [XTLS/Xray-docs-next#214]
### 问题参见：
[打开证书的时候提示没有权限](https://github.com/XTLS/Xray-core/issues/179#issue-787627030)

### 根本原因： 
上层路径 */home/vpsadmin* 无可执行（**x**）权限

### 处理方式:
给上层路径增加可执行权限
```bash
chmod +x /home/vpsadmin
```

希望能在的文档的注意事项中进行补充

**Comment by Fangliding** [comment]
22年的就先关了 如果现在还是可以复现请重发 给整个文件夹加可执行权限也不太行的样子
