### ISSUE TITLE
貌似反代配置中的bridge和portal写反了

### ISSUE THREAD

**Issue by PaTTeeL** [XTLS/Xray-docs-next#222]
https://github.com/XTLS/Xray-docs-next/blob/main/docs/config/reverse.md

> 假设在主机 A 中有一个网页服务器，这台主机没有公网 IP，无法在公网上直接访问。另有一台主机 B，它可以由公网访问。现在我们需要把 B 作为入口，把流量从 B 转发到 A。
> 在主机 A 中配置 Xray，称为bridge，在 B 中也配置 Xray，称为 portal。
> bridge 会向 portal 主动建立连接，此连接的目标地址可以自行设定。portal 会收到两种连接，一是由 bridge 发来的连接，二是公网用户发来的连接。portal 会自动将两类连接合并。于是 bridge 就可以收到公网流量了。
> bridge 在收到公网流量之后，会将其原封不动地发给主机 A 中的网页服务器。当然，这一步需要路由的协作。

如题，内网的服务器应该是portal，而公网服务器是bridge，所以在portal的配置中有bridge字段（需要指定对应的brdige），在bridge当中要指定对应的portal，按照逻辑也是bridge合并转发流量，portal则是出口端，负责最后的出口访问。

**Comment by Fangliding** [comment]
文档是对的 就是确实有点难读
