### ISSUE TITLE
建议在连接起VPS后设置防火墙放行需要的端口或者关闭防火墙，这样才好进行后续的操作。

### ISSUE THREAD

**Issue by Rain33** [XTLS/Xray-docs-next#233]
我是用的vultr的vps，跟着教程搭建时，在第4章更改端口后不能使用新设置的端口连接vps，经过请教大佬，后面发现把vps防火墙关闭后就可以用新端口连接起vps了。我再次新开vps根据教程改端口时一样遇到这个问题，经过设置防火墙允许放行设置的端口后就解决了这个问题。希望对遇到同样问题的朋友有帮助。

**Comment by Fangliding** [comment]
不同的服务商网页防火墙不可能全部照顾到
