### ISSUE TITLE
设置透明代理后，xray占用系统资源非常高

### ISSUE THREAD

**Issue by fengchen-github** [XTLS/Xray-docs-next#236]
cpu达到200%~300%，内存达到80%以后甚至out of memory，按https://xtls.github.io/document/level-2/tproxy.html#%E9%85%8D%E7%BD%AE%E6%B0%B8%E4%B9%85%E5%8C%96%E4%B8%8E%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF这个教程配置的，
这个配置有没有更新？

**Comment by phoenixxie0** [comment]
因为这个配置是把所有的流量都打上标记，然后转发到xray上进行处理，xray的路由配置如果有国内外分流，就会在这里进行分流，如果没有分流，就会全部走默认出口。
如果需要降低资源使用，可以考虑使用ipset设定gfwlist进行分流（iptables操作），也可以用nftset之类的操作。具体可以自行搜索。
