### ISSUE TITLE
【第 7 章】 Xray 服务器篇 - 终于等到你

### ISSUE THREAD

**Issue by wyshn** [XTLS/Xray-docs-next#301]
请教，这个最终还是做不通。前面都没问题。最后的时候

做到第7.9步。https打不开网站，是哪里有问题吗？

**Comment by Pandas711** [comment]
我也遇到这个问题了，7.9可以跳转https但是一直都是ERR_CONNECTION_TIMED_OUT，不知道如何解决

**Comment by Hr1114** [comment]
我也一样啊 7.8做完以后打不开网页了 请问解决了没有

**Comment by Hr1114** [comment]
显示重定向次数过多 尝试了清理缓存cookie

**Comment by suchacutesnake** [comment]
这个问题可能已经解决了，详见：https://github.com/XTLS/Xray-docs-next/pull/319
