### ISSUE TITLE
小小白白话文7.4 配置 Xray示例配置有误

### ISSUE THREAD

**Issue by palemoons** [XTLS/Xray-docs-next#323]
尝试使用示例配置文件运行时发现如下报错：

> 2023/02/02 05:47:53 [Warning] [3162575646] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to use xtls-rprx-direct, maybe "security" is not "xtls"

将配置文件中inbounds部分的streamSettings修改为以下配置之后，服务正常运行：

```
"streamSettings": {
    "network": "tcp",
    "security": "xtls",
    "xtlsSettings": {...}
  }
```

其中security字段改为`xtls`，tlsSettings改为`xtlsSettings`。
请检查是否确为错误，如果是麻烦修改🙂

**Comment by Fangliding** [comment]
更新核心
