### ISSUE TITLE
【第 5 章】网站建设篇的问题 

### ISSUE THREAD

**Issue by Zero1System** [XTLS/Xray-docs-next#364]
创建一个简单网页后，重启nginx，在chrome浏览器无法访问，看了5.4常见错误也没有解决，最后在IE浏览器终于能正常打开网页，但是在chrome浏览器无法正常显示，打开调试窗口出现VM629:6747 crbug/1173575, non-JS module files deprecated.错误，暂时不知道什么原因

**Comment by Fangliding** [comment]
no more information
