### ISSUE TITLE
如何自行构建文档

### ISSUE THREAD

**Issue by liyuankunbix** [XTLS/Xray-docs-next#380]
首先，向XProject的各位表达最真诚的感谢，是你们带我走出了茫茫无边的黑暗！

其次，想请问如何从本仓库的源码构建出html格式的文档，github.io的各种你懂的问题导致我对XProject的在线文档将来是否能正常访问表示担忧，希望能构建一套本机的过构建局域网内的文档站点，也愿意力所能及的条件下作为传递火炬的人在必要的时候搭建一套备用站点

然后，如果并非用于特殊的那种需求，而是单纯在非互联网的局域网内部使用，是否与小小白白话文的区别只是使用自签名证书代替Let's Encrypt签发的证书？

最后，再次感谢！

**Comment by Fangliding** [comment]
请参考 action 文件
