### ISSUE TITLE
5.4补充 （Nginx出现403的解决方案）

### ISSUE THREAD

**Issue by EricYoung37** [XTLS/Xray-docs-next#388]
如果按照教程走（没有写错路径），却在加载页面时出现403，则修改
`/etc/nginx/nginx.conf`中的`user www-data;`那一行为`user <你在教程第3章创建的拥有sudo权限的用户名>;`（不含括号）

简单来说这个配置文件这一行告诉Nginx以`www-data`身份运行Nginx并访问配置文件中的文件夹，这个身份很可能没有权限访问导致无法加载资源，因此要换成有权限的身份

花了2个小时在这上面....

[参考来源](https://stackoverflow.com/questions/20182329/nginx-is-throwing-an-403-forbidden-on-static-files)

**Comment by RPRX** [comment]
可以直接 PR
