### ISSUE TITLE
小小白白话文中7.4节配置与配置指南矛盾

### ISSUE THREAD

**Issue by immortal-boy** [XTLS/Xray-docs-next#399]
配置指南中描述disableSystemRoot默认为false，并且“当值为 true 时，Xray 只会使用 certificates 中指定的证书进行 TLS 握手。当值为 false 时，Xray 只会使用操作系统自带的 CA 证书进行 TLS 握手。”
而小小白白话文中7.4节配置未指定disableSystemRoot，因此certificates中的配置就不会被使用，而且7.3节整节都在描述这个不会被使用的证书。

**Comment by Fangliding** [comment]
@5e2t 池沼文档有一个问题挺大就是没有很明显地区分出客户端和服务端的应填配置 相比之下隔壁SB就严谨一些
