### ISSUE TITLE
白话文7.3 crontab执行sudo命令？

### ISSUE THREAD

**Issue by EYW-015** [XTLS/Xray-docs-next#425]
[小小白白话文 7.3](https://xtls.github.io/document/level-0/ch07-xray-server.html#_7-3-%E7%BB%99-xray-%E9%85%8D%E7%BD%AE-tls-%E8%AF%81%E4%B9%A6)

自动更新证书的`xray-cert-renew.sh`文件中
对服务重启的命令为`sudo systemctl restart xray`
但下方的自动任务操作`crontab -e`是对**非root的当前用户**
crontab难道可以执行sudo命令且无需输入密码么

是否应该先`sudo su`切换为root用户
再`crontab -e`编辑自动任务
或者使用`sudo crontab -u root -e`
`xray-cert-renew.sh`的重启命令修改为`systemctl restart xray`

如果我说错了请关闭issue

**Comment by chise0713** [comment]
>sudo su

sudo -i :

**Comment by EYW-015** [comment]
在`7.2 安装Xray`第二段和第三段都注明使用【非root用户】
`7.3`步骤中也未有提示使用`sudo -i`切换到root用户编辑crontab文件
那为何要在crontab运行的sh脚本中使用sudo命令

**Comment by Fangliding** [comment]
前面的sudo设置里已经添加了免密码使用
