### ISSUE TITLE
这算不算运行成功了？但是访问不了google

### ISSUE THREAD

**Issue by 725216** [XTLS/Xray-docs-next#519]
在openwrt上安装的，config.json是从win10上正常使用的v2rayn复制过来的，运行后显示如下：
root@ImmortalWrt:~# /etc/xray/xray run -c /etc/xray/config.json
Xray 1.8.16 (Xray, Penetrates Everything.) 9432a60 (go1.22.4 linux/mipsle)
A unified platform for anti-censorship.
2024/06/24 05:29:16 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
2024/06/24 05:29:18 [Warning] core: Xray 1.8.16 started

这是启动正常吗？

**Comment by Fangliding** [comment]
如果你说打开了 那确实是打开了 如果你说能不能上网 这里不处理wrt上乱七八糟的其他东西
