### ISSUE TITLE
语段重复

### ISSUE THREAD

**Issue by WilliamK7** [XTLS/Xray-docs-next#537]
使用指南-入门技巧-5.3 基于指定 IP 地址分流

`与 geosite.dat 规则文件十分类似的，我们还有 geoip.dat 这个规则文件，它是供【路由功能】驱使的第二个神兵利器，它致力于为用户提供成熟完善的【IP 分类表】。让用户可以简单的通过 geoip:xxx 这种格式方便的调用任何子类，定制符合自身需求的路由规则 。`

与 5.2 中重复，且 5.3 中没有必要出现这段话

**Comment by Fangliding** [comment]
唔 古代文档

**Comment by WilliamK7** [comment]
可以把文末的“最近更改”时间放到文章开头，让读者能注意到
