### ISSUE TITLE
x-ui面板会报xxx端口already in use,从而导致x-ui面板的core启动失败

### ISSUE THREAD

**Issue by adamgonglj** [XTLS/Xray-docs-next#539]
当使用https://github.com/MHSanaei/3x-ui/releases这个x-ui面板时，如果配置多个节点时，xray-core会启动失败，会报xxx端口already in use,从而导致x-ui面板的core启动失败。

能否在xray的机制中设定，定期关闭不活动的端口，从而避免端口被占用，65536个端口，几十个节点就就报端口已被占用，机制上或者端口资源请求上或多或少存在点问题。

我是很干净的服务器，就只安装另一个x-ui面板。

**Comment by AAkira45** [comment]
core如果都启动失败哪来的占用又如何释放？看下是不是存在多个core听说在运行，比如说同时使用了2个或以上的安装脚本，检查一下配置和端口占用情况看看是什么程序哪个路径在占用，该问题不是issue，建议再看看相关基础知识

**Comment by Fangliding** [comment]
1 我们不处理第三方面板/脚本遇到的问题
2 监听端口据我所知这样的面板都是随机分配的 不知道会不会检测端口是否被占用 不过这样的概率毕竟是很低的 大概是你手改的端口号和已有的服务或者其他入站造成了冲突
3 "定期关闭不活动的端口" 对于监听服务来说就没有这样的东西 不知道你从哪听来的
