### ISSUE TITLE
Some outdated documents

### ISSUE THREAD

**Issue by mmmray** [XTLS/Xray-docs-next#550]
Don't get me wrong, I didn't just recently discover this. But there's no discussion about it either, so let's start one.

* This is basically an outdated version of the README: https://xtls.github.io/en/document/install.html
  * I wanted to add this information for Windows 7, but the README is probably not the right place either: https://github.com/XTLS/Xray-core/pull/3530#issuecomment-2227224090
  * Many of the 3rd-party projects on that page are unmaintained
* The beginner tutorial is not very beginner, I think this is actually better served by youtube tutorials (and the real beginner nowadays just installs a panel): https://xtls.github.io/en/document/level-0/ch01-preface.html
* This seems entirely unmaintained, just delete it? https://xtls.github.io/en/about/news.html

I linked the english versions but the chinese docs have the same issue.

**Comment by Fangliding** [comment]
The introduction inside is generally correct, but the protocol used has not been updated. Even though I have many opinions about it, I don't have the energy or interest to refactor it. Like an old house, it can still be lived in after a few repairs
I just hope that the configuration section can keep up with the updates and update some old wording to make it better understood (some parts were once very vague and caused a lot of confusion for me before, until I rewrote it)
