### ISSUE TITLE
png 文件尺寸大有优化空间

### ISSUE THREAD

**Issue by Artoria2e5** [XTLS/Xray-docs-next#560]
由于本库 `git clone` 时消耗较长时间，我发现库内有多个超过 500 K 的 png 文件，严重怀疑用 `pngquant` 可以变小很多。提升用户浏览体验，也提升开发者体验。

**Comment by Fangliding** [comment]
其实是因为每次更新都会把build后的文件推送到 gh-pages 分支 导致这个分支存的历史数据过大 解决办法是fork仓库的时候选择仅fork main分支即可

**Comment by mmmray** [comment]
since the docs are already deployed to xtls.github.io repo, what is the use in having another gh-pages here?

**Comment by Artoria2e5** [comment]
并不是历史数据过大：clone --filter=tree:0 基本没有历史数据也要下载 5 MB 的图片！

**Comment by Fangliding** [comment]
> since the docs are already deployed to xtls.github.io repo, what is the use in having another gh-pages here?

Because the principle of github page is to publish a branch as a static asset on github.io

**Comment by mmmray** [comment]
what i mean is, in build.yml, the docs are built twice and deployed twice to different targets. once to the gh-pages of xtls.github.io, and once to the gh-pages of this repo. as a result, the docs are accessible from two different places:

https://xtls.github.io/Xray-docs-next/
https://xtls.github.io/
