### ISSUE TITLE
有一个关于内网的问题

### ISSUE THREAD

**Issue by daivinding** [XTLS/Xray-docs-next#591]
A端为手机或者其他移动设备
B端是服务器端
现在A端只能用通过B端跳外网，有木有办法A端可以通过B端连接到B端服务器所在的内网？现在从日志看，貌似数据A端出来以后，没有到达B端。V2RAYNG作为A端。
谢谢

**Comment by Fangliding** [comment]
要这么玩最好找dod借一段ip当内网 不然可能因为各层分流的绕过私有IP而出问题 涉及到各个GUI怎么设置的 核心本身没有限制 不处理这些问题
