### ISSUE TITLE
Page is truncated

### ISSUE THREAD

**Issue by wpdevelopment11** [XTLS/Xray-docs-next#593]
Source: https://github.com/XTLS/Xray-docs-next/blob/main/docs/document/level-2/tproxy.md
Rendered: https://xtls.github.io/document/level-2/tproxy.html

On the rendered page netfilter and iptables commands are not present.

**Comment by Fangliding** [comment]
Thank for report fixed in [3be606473ee05c28e47d9b76bebe17aeb8182d8d](https://github.com/XTLS/Xray-docs-next/commit/3be606473ee05c28e47d9b76bebe17aeb8182d8d)
