### ISSUE TITLE
[Feature] 深色模式与切换

### ISSUE THREAD

**Issue by SekiBetu** [XTLS/Xray-docs-next#6]
https://github.com/vuepress/awesome-vuepress 一些vuepress的资源集合，省的到处找主题和插件
https://github.com/Microflash/vuepress-theme-succinct 黑白两开花主题(强烈推荐用这个，白色晚上太刺眼了，这个主题有一个切换功能，点一下即可切成黑暗模式)

隔壁的Qv2ray的文档也是以这个主题为基础自己改了点东西，可以直接抄
https://github.com/Qv2ray/qv2ray.github.io/blob/source/package.json
https://github.com/Qv2ray/qv2ray.github.io/blob/source/patches/vuepress-theme-succinct%2B1.7.2.patch

**Comment by JimhHan** [comment]
感谢提议。
succinct 主题可能不是很适合，稍后写一个深色模式切换。

**Comment by JimhHan** [comment]
已在 0058f7012f6b1c28ebe04792d22e6aeee597b483 中添加深色模式。

**Comment by JimhHan** [comment]
已在 https://github.com/XTLS/Xray-docs-next/commit/6005718ccc3e97d21fbab7f367832e3ccb4f8064 中完成主题切换。
