### ISSUE TITLE
Splithttp needs to be updated

### ISSUE THREAD

**Issue by MHSanaei** [XTLS/Xray-docs-next#606]
splithttp (downloadSettings, mode, extra)
and 
TLS (pinnedPeerCertificatePublicKeySha256)

**Comment by Fangliding** [comment]
1 我的看法 https://github.com/XTLS/Xray-core/pull/3994#issuecomment-2469989414 后面可能会补吧
2 这个我注意到了 但是publickey hash并不是一个通用的证书参数 不去调用核心的代码或者自己写甚至没有合适的方式去计算它 我大概知道设计它的意图 但是这样一个瘸腿功能我还是想算了

**Comment by intmain0** [comment]
pinnedPeerCertificatePublicKeySha256这个功能还是挺有用的吧，可以防止恶意根证书
https://github.com/XTLS/Xray-core/discussions/4392#discussioncomment-12313869

**Comment by intmain0** [comment]
证书sha256计算方法
`openssl x509 -in isrgrootx1.pem -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64`

**Comment by Fangliding** [comment]
逐级验证这个特性以后会抽时间写一个pinnedPeerCertificateSha256做 publickey hash我不喜欢

**Comment by intmain0** [comment]
> 逐级验证这个特性以后会抽时间写一个pinnedPeerCertificateSha256做 publickey hash我不喜欢

ok……期待中

用这个功能主要是想验证根证书，防止恶意根证书
