### ISSUE TITLE
xHTTP page (ru)

### ISSUE THREAD

**Issue by iambabyninja** [XTLS/Xray-docs-next#618]
@RPRX  May I include a link to the Russian translation of your article in the xHTTP page?  
[LINK](https://github.com/XTLS/Xray-core/discussions/4113#discussioncomment-11468947)
The translation is currently fully synchronized with your original article.

For Russian-speaking users, if they have selected Russian as their documentation language, it would be much better for them to access the article directly in their local language.

**Comment by RPRX** [comment]
这两天我会更新文章，会在顶部 link RU 版本

**Comment by iambabyninja** [comment]
@RPRX Thank you so much for the release! I noticed that in the original post, you included a link to the Russian translation.

Could I update the links in the Russian documentation at https://xtls.github.io/ru/ to point to the Russian version of your post about xHTTP? This way, users can directly access the relevant information.

**Comment by RPRX** [comment]
@iambabyninja 可以，同步新的内容后改一下 link 吧

**Comment by RPRX** [comment]
@iambabyninja 又更新了一些内容，还有我注意到上次有些内容没有被 RU 版本同步，不过我也觉得这项工作挺麻烦的，辛苦了

**Comment by iambabyninja** [comment]
> @iambabyninja 又更新了一些内容，还有我注意到上次有些内容没有被 RU 版本同步，不过我也觉得这项工作挺麻烦的，辛苦了

The translation is now 100% synchronized with the original post.
Once again, I want to express my gratitude to the entire team and to you personally for xray-core and all its cutting-edge solutions.
🤝❤️

**Comment by RPRX** [comment]
@iambabyninja 我注意到 Project VLESS 群组的置顶是 v24.12.18 release notes 的俄语版，我更新了第一段，还有可以 link 下文章

**Comment by iambabyninja** [comment]
@RPRX I wanted to clarify: did you intentionally move the xHTTP document to GitHub?
Perhaps the content could be transferred to the documentation website, at least the configuration structure?
The extended documentation could remain on GitHub.

**Comment by RPRX** [comment]
@iambabyninja 目前暂无将文章迁移至 xtls.github.io 的计划

**Comment by RPRX** [comment]
@iambabyninja 我发现最新版 RU 没有完全同步 XHTTP 第四版的内容，此外我又加了一段话
